# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: app-service-name
spec:
  selector:
    app: app-service-name
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: NodePort